import "bootstrap/dist/css/bootstrap.css"
import 'owl.carousel/dist/assets/owl.carousel.css';
import "./actiontext.scss";
import "./login.scss";
import "./postindex.scss";
import "./bubble.scss";
import "./message.scss"
import "./actiontext.scss"
import "./loading.scss"
