FACEBOOK_CLIENT_ID: "2415133365450082"
FACEBOOK_CLIENT_SECRET: "3d946bb0ccbe4c376d2c50a5a9ed2378"
GOOGLE_CLIENT_ID: "714931842994-umie7l3bfer4go1i7spa1coh7cvgmsan.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET: "VTiWoSGNxc5YvUMWrASRUlbm"